---
name: Build Docker Image

on:
  pull_request:
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile